### PR TITLE
Cdat panel with launcher

### PR DESCRIPTION
**Pull request by jbeezley**
@sterlingbaldwin This might be working, but I'm having trouble with my UV-CDAT install at the moment :/.  Anyway, you just need to define `VISUALIZATION_LAUNCHER` in local settings.

The import part of the code is [here](https://github.com/ACME-OUI/acme-web-fe/compare/cdat-panel?expand=1#diff-525d91d59075e0825aaa4c2de27389ceR204) where the RPC is performed.

Note: this is a race condition because my function expects the `#cdat-vis` node to exist when it is executed.  Besides that, I just need to attach resize handlers for when the dashboard view changes.  It shouldn't take to much longer once I get UV-CDAT running again.

### CODE REVIEW

**Comment by sterlingbaldwin** [comment]
what should the `VISUALIZATION_LAUNCHER` point to? is that the IP address of the vis server?

edit: never mind, I looked at the commits

**Comment by sterlingbaldwin** [comment]
Also thanks for this! Looks good to me.

**Comment by sterlingbaldwin** [comment]
@jbeezley Do you know if the vis server on aims1 is working? And what port its running on?

**Comment by jbeezley** [comment]
> what should the VISUALIZATION_LAUNCHER point to? is that the IP address of the vis server?

Yes.  `http://localhost:7000/vtk` if you start it locally.

> Do you know if the vis server on aims1 is working? And what port its running on?

Probably not working, it would need an update anyway.  I tried to log in, but

```
$ ssh -vvv aims1.llnl.gov
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 102: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to aims1.llnl.gov [198.128.245.180] port 22.
debug1: Connection established.
debug3: Incorrect RSA1 identifier
debug3: Could not load "/Users/jbeezley/.ssh/id_rsa" as a RSA1 public key
debug1: identity file /Users/jbeezley/.ssh/id_rsa type 1
debug1: identity file /Users/jbeezley/.ssh/id_rsa-cert type -1
debug1: identity file /Users/jbeezley/.ssh/id_dsa type -1
debug1: identity file /Users/jbeezley/.ssh/id_dsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2
ssh_exchange_identification: read: Connection reset by peer
```

Does somebody need to reconfigure my IP in the firewall?

**Comment by sterlingbaldwin** [comment]
Sam and I have been having some issues with the aims1 firewall ourselves. When was the last time you were able to get in? A couple weeks ago, someone in the networking department put up a firewall for like 2 or 3 days that completely blocked access to everyone. I was able to ssh in yesterday, but maybe this is an external facing issue and doesnt effect internal access.

**Comment by jbeezley** [comment]
It was quite a while ago that I last accessed it.  I tried just after they took down ESGF, and it didn't work then.  I assumed they had just reconfigured the firewall.  Interestingly, I'm not blocked completely from accessing port 22 (I can connect to it via telnet).  It seems to disconnect the connection after my client sends the authentication request.

**Comment by sterlingbaldwin** [comment]
Thats super annoying. I'll talk to Tony on monday and see if he can help. Ill message you and we can try and work this out.

**Pull request merged**
