### PR TITLE
[WIP] cdat panel

### PR DESCRIPTION
**Pull request by jbeezley**
@sterlingbaldwin This is by no means useable yet, but I though I would give you a heads up on the API I'm adding for this.  It should be relatively straightforward, but let me know if you have any _questions, comments, or snide remarks_™.

### CODE REVIEW

**Comment by jbeezley** [comment]
@mattben `[WIP]` generally means "not ready to merge yet".  :P

**Comment by mattben** [comment]
@jbeezley then why go there the trouble of making a pull request? my bad.

**Comment by jbeezley** [comment]
To notify others what you are doing.  Especially when others might have comments about it.

**Comment by sterlingbaldwin** [comment]
Thanks @jbeezley ! Ill look at this and see what I can see.

**Comment by jbeezley** [comment]
Just try not to see what you can't see.  That can be dangerous.

**Pull request merged**
