### PR TITLE
Integrates velo to work with mtree and display the users files 

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
- Fixes some pep8 issues.
- Adds codemirror. It doesnt do anything yet, but im just getting started with it.
- Adds a testing folder and the robotframework, as well as an initial test.
- Changes the VeloAPI.py so that it returns the folder contents in a list, instead of just printing to the screen.
- Gets velo and mtree to display, and allow the user to interact with, their user folder contents.

Finally, please ignore the fact that I have like 80 commits with the same message. I was basically using git as rsync to move my changes to aims1 and back, just so my code was the same in several places at once. I havent figured out how to rebase after pushing to the remote repo or I would squash them all into one commit.

### CODE REVIEW

**Comment by jbeezley** [comment]
You can use `git push -f` to force push a rebased branch.

**Comment by mattben** [comment]
@sterlingbaldwin the build is broken :(

**Comment by sterlingbaldwin** [comment]
Adds functionality so the user can now click on a file from the tree and have it populate in the code editor.

And ya, tried to figure out how to rebase it, and again failed... :(

**Comment by mattben** [comment]
looks good this time.

**Pull request merged**
