### PR TITLE
Autosync will actually work... mostly

### PR DESCRIPTION
**Pull request by chaosphere2112**
Makes auto sync to JIRA work perfectly for creating new issues (does not currently sync updates). That's the next thing on the list.

### CODE REVIEW

**Comment by mattben** [comment]
@Sam :-1:

**Comment by chaosphere2112** [comment]
Yeah, yeah; I'm just writing up the update logic now, and sticking it all into the one PR. That'll also fix the pep8.

**Comment by chaosphere2112** [comment]
@mattben Alright, there you go. Are you happy now?

**Comment by sterlingbaldwin** [comment]
Im merging this since all the tests are passing. :hamster:

**Comment by sam** [comment]
Wrong @sam. :-)

**Comment by chaosphere2112** [comment]
Nice name, though :wink:

**Comment by mattben** [comment]
Sorry... @Sam :smile: @chaosphere2112 you really need a better name :imp:

**Comment by chaosphere2112** [comment]
Well, the other guy took mine!

**Pull request merged**
