### PR TITLE
Fixes the issue with page loading when ESGF is down

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
Since the ESGF nodes are going to be down for a while, I added a timeout for the node info request, where if it times out the dashboard will load, just with no nodes. Also adds labels for users adding new credentials, so they can see which ones they already have.

### CODE REVIEW

**Comment by sterlingbaldwin** [comment]
Travis is failing because the tests cant connect to the ESGF nodes. If anything this shows the tests actually work.

**Comment by chaosphere2112** [comment]
I'm going to merge; this is failing right now, in a more obnoxious fashion (ridiculously long time-out).

**Comment by sterlingbaldwin** [comment]
I see this as a short term solution until we have the ESGF nodes back online. Later if we want to do something more drastic, we can go there, but for the time being I just want the site to work.

**Comment by chaosphere2112** [comment]
:+1:

**Pull request merged**
