### PR TITLE
First couple tests

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
Adds the first couple selenium tests, as well as two unit tests for django.

### CODE REVIEW

**Comment by chaosphere2112** [comment]
@sterlingbaldwin Looks good; how about you add running the tests to the Travis build process?

**Comment by jbeezley** [comment]
Here is how to get started with selenium on travis: http://docs.travis-ci.com/user/gui-and-headless-browsers/

Getting it working with saucelabs would be awesome.

**Comment by chaosphere2112** [comment]
Yeah, getting the saucelabs integration would be nice; for this PR, though, I'm thinking we'll stick to just the backend tests, so we don't need to sit around waiting for the purchase of the license. Also, we're planning on getting a Jenkins server set up for some CI on our devel instance, so we can run the selenium tests on there once it's configured.

**Comment by jbeezley** [comment]
What license?  Saucelabs is free for open source projects.

**Comment by chaosphere2112** [comment]
@jbeezley Totally missed that on their site; I'll take a look at getting those integrated right now.

**Comment by jbeezley** [comment]
Another tip.  If you add `sudo: false`, your test will be run in a docker container that will start up and run **much** faster.

**Comment by chaosphere2112** [comment]
Woo! Passing tests. Now I'll just figure out getting selenium running. I'm thinking we can just use PhantomJS, since it's pre-installed on travis. Easier than setting up another third party integration.

**Comment by sterlingbaldwin** [comment]
PhantomJS is built into Jenkins, but it looks like Travis should be fairly easy to setup up for it too.

http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-PhantomJS

**Comment by chaosphere2112** [comment]
Well, how about I just get the jenkins server set up, then? That'll probably do.

**Comment by sterlingbaldwin** [comment]
One thing to keep in mind, is that the Travis output needs to be checked manually. I dont think if a test fails, if Travis will say the build failed.

**Comment by chaosphere2112** [comment]
If a test fails, it should exit with a status of 1 instead of a status of 0. Shouldn't need to check the output.

**Comment by sterlingbaldwin** [comment]
Never mind then! I mean, how could I know, when all my tests work so well ;)

**Comment by mattben** [comment]
So much good content in the comments and then I get to the bottom and Travis failed. What a let down. @sterlingbaldwin why it no working

**Comment by sterlingbaldwin** [comment]
It was all pep8 issues. I think I fixed them all, just waiting to hear back from Travis.

**Comment by sterlingbaldwin** [comment]
Travis is failing because it doesnt have jpype. The tests all pass when you run them, but Travis is marking the build as failed anyway.

**Comment by sterlingbaldwin** [comment]
Hopefully these changes will solve the problem. Got to wait for Travis to start up though ...

**Comment by sterlingbaldwin** [comment]
OK! I commented out the velo tests for the time being. For the record, they run fine locally, and on aims1, its just when Travis runs them it fails for some reason. Also I fixed the velo path issue.

**Comment by jbeezley** [comment]
I didn't look into specifically what your test is trying to do, but the error message emitted is telling you that it requires a running X server.  [This](http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-%28e.g.-a-Web-browser%29) describes how to start up a virtual X server that will work for most things that don't require GL.

**Comment by sterlingbaldwin** [comment]
All the test did was send a request using the velo api and check the result, none of which should have required any visualization. If we're going to get the CI server to do the front end tests, then we're going to need to do something like what you're talking about, but I dont want to jump into it until we've made that decision.

**Comment by jbeezley** [comment]
I know literally nothing about java, but inspecting the VeloAPI jar, it clearly contains a lot of GUI junk inside.  For whatever reason, an X server will be required to start the VeloAPI server.

**Comment by mattben** [comment]
@jbeezley I'll let @bibiraju explain the jar to you. My understanding is its just a repackaging of there server client with a python wrapper using Jpype. Its large and over kill but is working on the prod and devel server. I was going to let this issue slide for the time being since it works.

**Comment by bibiraju** [comment]
@jbeezley I agree that the VeloAPI jar contains many unwanted files and jars. As Matthew explained its just a repackaging of Velo client application. We did not want to spend much time on creating a specific jar as its not at the top of priority, I can work on cleaning up the jar if we all think its important.

**Comment by sterlingbaldwin** [comment]
I dont think its worth the time at the moment. The only issue is that the headless testing doesnt like it, but thats only because it doesnt have the X server installed. As soon as we get CI doing the Selenium tests this wont be an issue anymore.

**Comment by jbeezley** [comment]
Sure, I was just explaining why travis wouldn't start the server.  It isn't that big of a deal to start a virtual X server.  The main thing you lose is the ability to run in the faster and more stable travis containers because you need root access.

**Pull request merged**
