### PR TITLE
Issues test + duplicate issue fix

### PR DESCRIPTION
**Pull request by chaosphere2112**
Added some basic tests of the model functionality, and made it so selenium tests would be run by nose. This will probably crash horribly on Travis, so I'll fix it once I see what's up.

### CODE REVIEW

**Comment by mattben** [comment]
@chaosphere2112 ???

**Comment by chaosphere2112** [comment]
@mattben Sorry, forgot to provide some default values to the settings

**Comment by chaosphere2112** [comment]
@mattben @sterlingbaldwin Ok, this passes all tests locally and on a VM configured with XVFB. I think Travis is the guilty party here. Setting up an alternative testing solution is beyond the scope of this PR; when we have some spare cycles, I think we should offload selenium testing to a Jenkins instance on AIMS1 or something. It looks like it'll be pretty easy to configure Apache to only allow GitHub and Lab IPs to access the server, so I think that should be the plan (for when we have the time). In the meantime, how about we just merge this and call it a day?

**Comment by mattben** [comment]
@chaosphere2112 so merge this on your word? I'll do it

**Comment by chaosphere2112** [comment]
I'll merge from master first

**Comment by sterlingbaldwin** [comment]
@chaosphere2112 I fixed the pep8 issue that was stopping the travis build. If you just do an empty commit to force travis to start again we can see if your fixes work. Not sure if there is a way to just force travis to go, it would be handy if there was.

**Comment by chaosphere2112** [comment]
I can just trigger a rebuild of the same code; it’s going now.

**Comment by sterlingbaldwin** [comment]
I fixed this issue in master, but travis must be testing your branch which still has it. Its just a space after a '+' in apps/velo/tests.py

**Comment by sterlingbaldwin** [comment]
I think if we merge my PR I think it will fix this issue?

**Comment by mattben** [comment]
@sterlingbaldwin how do I make it re run the tests?

**Pull request merged**
