### PR TITLE
User is now logged in after registration

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
Does what it says on the tin.

### CODE REVIEW

**Comment by chaosphere2112** [comment]
make a test

**Comment by sterlingbaldwin** [comment]
Ill get those TPS reports in while Im at it.

**Comment by chaosphere2112** [comment]
:+1:

**Comment by mattben** [comment]
:+1: like to infinity for that PR comment @chaosphere2112 :trophy:

**Comment by sterlingbaldwin** [comment]
On further reflection, I remember now that we have a captcha in place specifically to make automatic registration impossible. Ill have this test done as soon as my optical character recognition can beat the google recaptcha. Until then we're just going to have to manually test the registration functionality.

**Comment by chaosphere2112** [comment]
You sassin' me boy? :bomb:

**Comment by chaosphere2112** [comment]
Erm, you could wrap the recaptcha validation with a check to see if it's a test environment.

**Comment by sterlingbaldwin** [comment]
That's out of the scope of this issue. If thats something we're going to do, it should be its own thing. For the time being just hit that big green merge button and lets move on with our lives. :D

**Comment by chaosphere2112** [comment]
Fair enough.

**Pull request merged**
