### PR TITLE
Sets up the velo service layer

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
This set of commits creates the velo_service.py, which is a stand-alone werkzeug http server to store velo instances and make requests with the VeloAPI.py. All velo requests now go through this service. Extending it should be fairly simple when we want to make use of more velo api calls, or create additional functionality.

This PR also updates all the velo tests, as well as the selenium tests, to work with the new velo service as well as the changes made to the user interface.

### CODE REVIEW

**Comment by sterlingbaldwin** [comment]
There is a funky issue where the velo api is throwing a java runtime exception, but after extensive manual and automatic testing, this only happens when its run with an automated test.

**Comment by sterlingbaldwin** [comment]
Yay! I had to remove a couple of the asserts from the velo tests because of travis. Although I know this is bad form, I believe this is 100% a travis environment issue and nothing to do with the code itself. I still think we should go to Jenkis CI since it will give us a much greater level of control over the testing process, and allow for builds to be pushed to the dev or production servers automatically, but I also realize that this would be a bit of work to setup properly.

**Comment by sterlingbaldwin** [comment]
Also of note here is that I removed the selenium tests from being run by travis completely. They are all passing, and we should continue to update them (and check them!) as we move forward, but travis just isnt the platform that should do that sort of test. 

A good policy moving forward would be for developers to not only have to add a back end and front end test for each new UI feature, but to copy paste an image of the tests passing (or something, just to ensure that people are a) writing tests, and b) actually running them)

**Comment by sterlingbaldwin** [comment]
screen shot 2015-07-30 at 2 09 45 pm

**Comment by mattben** [comment]
@sterlingbaldwin conflicts, I can't merge from the browser please fix

**Comment by sterlingbaldwin** [comment]
Should I just merge it myself from the commandline?

**Pull request merged**
